name: WishGift
version: ${project.version}
main: cn.marinda.wishgift.WishGift
authors: [ Marinda ]
description: this Spigot Plugins description
softdepend: [VexView,Vault,PlayerPoints,PlaceHolderAPI]
commands:
  wg:
    description: "description"
    usage: /wg
    aliases: [wg]

